version: "3.8"

services:
  bot:
    build: .
    container_name: snel-telegram-bot
    restart: unless-stopped
    env_file:
      - .env.prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
