name: Deploy to Hetzner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            set -e
            echo "Starting deployment..."

            # Ensure directory exists and is clean
            rm -rf /opt/snel-telegram/*
            mkdir -p /opt/snel-telegram
            cd /opt/snel-telegram

            # Copy repository files
            echo "Copying repository files..."
            cp -r /home/snel-bot/stable-snel-tg/* .

            # Create .env file
            echo "Setting up environment..."
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

            echo "Stopping existing containers..."
            docker-compose down || true

            echo "Building container..."
            docker-compose build --no-cache

            echo "Starting container..."
            docker-compose up -d

            echo "Waiting for container to start..."
            sleep 10

            echo "Checking container status..."
            docker ps | grep snel-telegram-bot

            echo "Checking container logs..."
            docker logs snel-telegram-bot
