name: Deploy to Hetzner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment package
        run: |
          # Create a clean deployment directory
          mkdir -p deploy
          cp bot.py docker-compose.yml Dockerfile requirements.txt deploy/

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          source: "deploy/*"
          target: "/opt/snel-telegram"
          strip_components: 1

      - name: Start bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /opt/snel-telegram

            # Set up environment
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

            # Run Docker
            docker compose down || true
            docker compose up -d --build

            # Verify deployment
            echo "Container status:"
            docker ps | grep snel-telegram-bot || echo "Container not running!"
            echo "Container logs:"
            docker logs snel-telegram-bot
