name: Deploy to Hetzner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            set -e
            echo "Starting deployment..."

            # Debug: Show current user and directory
            echo "Running as user: $(whoami)"
            echo "In directory: $(pwd)"

            # Ensure directory exists and is clean
            sudo rm -rf /opt/snel-telegram/*
            sudo mkdir -p /opt/snel-telegram
            sudo chown -R $(whoami):$(whoami) /opt/snel-telegram
            cd /opt/snel-telegram

            # Set up SSH for GitHub
            echo "Setting up SSH config..."
            sudo mkdir -p /root/.ssh
            echo "${{ secrets.GIT_SSH_KEY }}" | sudo tee /root/.ssh/github_deploy_key > /dev/null
            sudo chmod 600 /root/.ssh/github_deploy_key

            # Add GitHub's host key
            echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" | sudo tee -a /root/.ssh/known_hosts > /dev/null

            # Configure Git to use the deploy key
            export GIT_SSH_COMMAND="ssh -i /root/.ssh/github_deploy_key -o IdentitiesOnly=yes"

            # Test Git connection
            echo "Testing Git connection..."
            ssh -i /root/.ssh/github_deploy_key -o IdentitiesOnly=yes git@github.com || true

            # Clone the repository
            echo "Cloning repository..."
            git clone git@github.com:sneldao/stable-snel-tg.git .

            # Debug: Show cloned files
            echo "Cloned files:"
            ls -la

            # Create .env file
            echo "Setting up environment..."
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

            echo "Stopping existing containers..."
            docker-compose down || true

            echo "Building container..."
            docker-compose build --no-cache

            echo "Starting container..."
            docker-compose up -d

            echo "Waiting for container to start..."
            sleep 10

            echo "Checking container status..."
            docker ps | grep snel-telegram-bot || echo "Container not found!"

            echo "Checking container logs..."
            docker logs snel-telegram-bot 2>&1 || echo "No logs available"
