name: Deploy to Hetzner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          source: "bot.py,docker-compose.yml,Dockerfile,requirements.txt"
          target: "/opt/snel-telegram"
          strip_components: 0

      - name: Start bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /opt/snel-telegram

            # Set up environment
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

            # Ensure correct permissions
            chown -R root:root .
            chmod -R 644 .
            chmod 755 .
            chmod 600 .env

            # Run Docker
            docker compose down || true
            docker compose up -d --build

            # Show deployment status
            echo "Waiting for container to start..."
            sleep 5
            echo "Container status:"
            docker ps | grep snel-telegram-bot || echo "Container not running!"
            echo "Container logs:"
            docker logs snel-telegram-bot 2>&1 || echo "No logs available"
