name: Deploy to Hetzner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            set -e
            echo "Starting deployment..."

            # Debug: Show current user and directory
            echo "Running as user: $(whoami)"
            echo "In directory: $(pwd)"

            # Ensure directory exists and is clean
            sudo rm -rf /opt/snel-telegram/*
            sudo mkdir -p /opt/snel-telegram
            sudo chown -R $(whoami):$(whoami) /opt/snel-telegram
            cd /opt/snel-telegram

            # Clone the repository using HTTPS
            echo "Cloning repository..."
            git clone https://github.com/sneldao/stable-snel-tg.git .

            # Debug: Show cloned files
            echo "Cloned files:"
            ls -la

            # Create .env file
            echo "Setting up environment..."
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

            echo "Stopping existing containers..."
            docker-compose down || true

            echo "Building container..."
            docker-compose build --no-cache

            echo "Starting container..."
            docker-compose up -d

            echo "Waiting for container to start..."
            sleep 10

            echo "Checking container status..."
            docker ps | grep snel-telegram-bot || echo "Container not found!"

            echo "Checking container logs..."
            docker logs snel-telegram-bot 2>&1 || echo "No logs available"
