name: Deploy to Hetzner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test directory access
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            echo "Testing access to /opt/telegram-bot"
            ls -la /opt/telegram-bot
            echo "Directory exists and is accessible"

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          source: "bot.py,docker-compose.yml,Dockerfile,requirements.txt"
          target: "/opt/telegram-bot"
          strip_components: 0

      - name: Deploy bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /opt/telegram-bot

            # Create .env file
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

            # Stop existing container
            docker compose down || true

            # Build and start new container
            docker compose up -d --build

            # Show status
            echo "CONTAINER STATUS:"
            docker ps | grep telegram-bot || echo "Container not running!"

            echo "LOGS:"
            sleep 5
            docker logs snel-telegram-bot 2>&1 || echo "No logs available"
