name: Deploy to Hetzner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            set -e
            echo "Starting deployment..."

            # Ensure directory exists and is clean
            rm -rf /opt/snel-telegram/*
            mkdir -p /opt/snel-telegram
            cd /opt/snel-telegram

            # Set up SSH config for GitHub
            echo "Setting up SSH config..."
            mkdir -p ~/.ssh
            echo "${{ secrets.GIT_SSH_KEY }}" > ~/.ssh/github_deploy_key
            chmod 600 ~/.ssh/github_deploy_key
            echo -e "Host github.com\n  IdentityFile ~/.ssh/github_deploy_key\n  StrictHostKeyChecking no" > ~/.ssh/config

            # Clone the repository
            echo "Cloning repository..."
            git clone git@github.com:sneldao/stable-snel-tg.git .

            # Create .env file
            echo "Setting up environment..."
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

            echo "Stopping existing containers..."
            docker-compose down || true

            echo "Building container..."
            docker-compose build --no-cache

            echo "Starting container..."
            docker-compose up -d

            echo "Waiting for container to start..."
            sleep 10

            echo "Checking container status..."
            docker ps | grep snel-telegram-bot || echo "Container not found!"

            echo "Checking container logs..."
            docker logs snel-telegram-bot 2>&1 || echo "No logs available"
